### PR TITLE
Making config.json work with cwd

### PR DESCRIPTION
**Pull request by ha6000**
Making config.json rather work with current working directory rather then dirname

### CODE REVIEW

**Comment by ha6000** [comment]
I saw that accounts.sqlite works with cwd, so I was just thinking that the config.json should too

**Comment by BeepIsla** [comment]
Wouldn't the same be needed in the `databaseManager.js`?

**Comment by ha6000** [comment]
Ahh I forgot about that, I will do it now

**Comment by BeepIsla** [comment]
Thanks for your contribution

**Pull request merged**
