### PR TITLE
fixed commendbot again

### PR DESCRIPTION
**Pull request by ghost**
fixed it again, now it takes one minute, after all accounts login, to start commending

### CODE REVIEW

**Comment by ghost** [comment]
a lower number could also work, but I didnt test it

**Comment by Paulbmad** [comment]
yea its also works for report section thanks.

**Comment by Nasri69** [comment]
can now report midgame ? @Paulbmad

**Review by trustyuy — APPROVED** [review]

**Review by Nasri69 — APPROVED** [review]

**Comment by Nasri69** [comment]
@inbroso patch again :(

**Comment by lightbgs** [comment]
@inbroso it just got patched again

**Comment by ghost** [comment]
yeah its outdated again wtf

**Comment by FraanArrizu** [comment]
outdated again :(

**Comment by markito12** [comment]
#593

**Pull request closed without merging**
