### PR TITLE
Commendbot Fix

### PR DESCRIPTION
**Pull request by inbroso**
I did a little fix to the commendbot. Now it is fully working again. The solution isnt as nice as you might expect, but it works.
I just had to do a little change in the index.js at row 400 to 405.
The solution is to just preload the chunks which I implemented and then I always got 19/20 or 20/20.
Maybe you could implement this little fix or even enhance it, so it doesn't look so provisional.

There is no need for proxies etc.

image

### CODE REVIEW

**Comment by kezyon210** [comment]
what version is

**Comment by kezyon210** [comment]
SyntaxError: Identifier 'result' has already been declared

**Comment by inbroso** [comment]
> SyntaxError: Identifier 'result' has already been declared

Neither me nor my friends had this problem.
Are you sure you installed it correctly and are you sure you got the right nodeJS Version?
https://github.com/BeepIsla/csgo-commend-bot/tree/bc8435003e92db917a6c87dc700a0ec56f867802#installation

**Comment by kezyon210** [comment]
yea

**Comment by inbroso** [comment]
Everyone I sent it to said it worked. And I also did a "clean install" of the commendbot and it still works for me.
And you are absolutely sure that you have installed node-v12.9.1-x64.msi and not a newer/older version?

**Comment by rabell69** [comment]
@inbroso great work <3

**Comment by kezyon210** [comment]
C:\Users\Nicolas\Desktop\csgobot\index.js:403
                let result = await handleChunk(chunks[i], (targetAcc instanceof Target ? targetAcc.accountid : targetAcc), serverToUse, matchID);
                    ^

SyntaxError: Identifier 'result' has already been declared
[90m    at Module._compile (internal/modules/cjs/loader.js:872:18)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:790:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:703:12)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m
PS C:\Users\Nicolas\Desktop\csgobot>

**Comment by inbroso** [comment]
Seems like you downloaded it wrong or something in this direction.
Because Line 403 isnt the line with let result: https://github.com/BeepIsla/csgo-commend-bot/blob/2a18bd13cc79fa443489c83bddb7d20b433c53c3/index.js#L403
You can try to copy the index.js out of the link I just posted. Then it should work.

**Comment by hyppr** [comment]
Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 15835 operational accounts
 Getting an available server
TypeError: helper.GetActiveServer is not a function
    at C:\Users\noahe\Downloads\csgo-commend-bot-master\csgo-commend-bot-master\index.js:196:31 Promise {
  <rejected> TypeError: helper.GetActiveServer is not a function
      at C:\Users\noahe\Downloads\csgo-commend-bot-master\csgo-commend-bot-master\index.js:196:31
}

**Comment by inbroso** [comment]
> Up to date!
> Checking protobufs...
> Found protobufs
> Opening database...
> There are a total of 15835 operational accounts
> Getting an available server
> TypeError: helper.GetActiveServer is not a function
> at C:\Users\noahe\Downloads\csgo-commend-bot-master\csgo-commend-bot-master\index.js:196:31 Promise {
> TypeError: helper.GetActiveServer is not a function
> at C:\Users\noahe\Downloads\csgo-commend-bot-master\csgo-commend-bot-master\index.js:196:31
> }
I didn't write this commendbot, so I have no clue why you get this error message. And because I only changed about 4 lines of code, I really don't think it's a problem with my fixed version. Because on my PC it works and my friends say that it also works for them.
It might be an issue in the installation process, are you sure you have the right nodeJS version installed which is mentioned on the link below? And are you sure you ran "npm install"?
Just follow these instructions BeepIsla mentioned in his README:
https://github.com/BeepIsla/csgo-commend-bot/tree/bc8435003e92db917a6c87dc700a0ec56f867802#installation

**Comment by hyppr** [comment]
> > Up to date!
> > Checking protobufs...
> > Found protobufs
> > Opening database...
> > There are a total of 15835 operational accounts
> > Getting an available server
> > TypeError: helper.GetActiveServer is not a function
> > at C:\Users\noahe\Downloads\csgo-commend-bot-master\csgo-commend-bot-master\index.js:196:31 Promise {
> > TypeError: helper.GetActiveServer is not a function
> > at C:\Users\noahe\Downloads\csgo-commend-bot-master\csgo-commend-bot-master\index.js:196:31
> > }
> > I didn't write this commendbot, so I have no clue why you get this error message. And because I only changed about 4 lines of code, I really don't think it's a problem with my fixed version. Because on my PC it works and my friends say that it also works for them.
> > It might be an issue in the installation process, are you sure you have the right nodeJS version installed which is mentioned on the link below? And are you sure you ran "npm install"?
> > Just follow these instructions BeepIsla mentioned in his README:
> > https://github.com/BeepIsla/csgo-commend-bot/tree/bc8435003e92db917a6c87dc700a0ec56f867802#installation

could you find which lines of code you changed, and ill copy and paste them into my original index.js that worked

**Comment by inbroso** [comment]
> > > Up to date!
> > > Checking protobufs...
> > > Found protobufs
> > > Opening database...
> > > There are a total of 15835 operational accounts
> > > Getting an available server
> > > TypeError: helper.GetActiveServer is not a function
> > > at C:\Users\noahe\Downloads\csgo-commend-bot-master\csgo-commend-bot-master\index.js:196:31 Promise {
> > > TypeError: helper.GetActiveServer is not a function
> > > at C:\Users\noahe\Downloads\csgo-commend-bot-master\csgo-commend-bot-master\index.js:196:31
> > > }
> > > I didn't write this commendbot, so I have no clue why you get this error message. And because I only changed about 4 lines of code, I really don't think it's a problem with my fixed version. Because on my PC it works and my friends say that it also works for them.
> > > It might be an issue in the installation process, are you sure you have the right nodeJS version installed which is mentioned on the link below? And are you sure you ran "npm install"?
> > > Just follow these instructions BeepIsla mentioned in his README:
> > > https://github.com/BeepIsla/csgo-commend-bot/tree/bc8435003e92db917a6c87dc700a0ec56f867802#installation
> 
> could you find which lines of code you changed, and ill copy and paste them into my original index.js that worked

https://github.com/inbroso/csgo-commend-bot/blob/master/index.js

Go to line 400 and copy this:
image

One important thing: You MUST use Version 2.6.1. Otherwise it doesnt work!

**Comment by hyppr** [comment]
> > > > Up to date!
> > > > Checking protobufs...
> > > > Found protobufs
> > > > Opening database...
> > > > There are a total of 15835 operational accounts
> > > > Getting an available server
> > > > TypeError: helper.GetActiveServer is not a function
> > > > at C:\Users\noahe\Downloads\csgo-commend-bot-master\csgo-commend-bot-master\index.js:196:31 Promise {
> > > > TypeError: helper.GetActiveServer is not a function
> > > > at C:\Users\noahe\Downloads\csgo-commend-bot-master\csgo-commend-bot-master\index.js:196:31
> > > > }
> > > > I didn't write this commendbot, so I have no clue why you get this error message. And because I only changed about 4 lines of code, I really don't think it's a problem with my fixed version. Because on my PC it works and my friends say that it also works for them.
> > > > It might be an issue in the installation process, are you sure you have the right nodeJS version installed which is mentioned on the link below? And are you sure you ran "npm install"?
> > > > Just follow these instructions BeepIsla mentioned in his README:
> > > > https://github.com/BeepIsla/csgo-commend-bot/tree/bc8435003e92db917a6c87dc700a0ec56f867802#installation
> > 
> > 
> > could you find which lines of code you changed, and ill copy and paste them into my original index.js that worked
> 
> https://github.com/inbroso/csgo-commend-bot/blob/master/index.js
> 
> Go to line 400 and copy this:
> image
> 
> One important thing: You MUST use Version 2.6.1. Otherwise it doesnt work!

i found that and copied the code in, but i realised i think i might have the wrong version. where can i download version 2.6.1?

**Comment by BeepIsla** [comment]
This should now hopefully be fixed. It worked in my small test, might have some problems with `LOGIN` method, I don't know. [Try it out!](https://github.com/BeepIsla/csgo-commend-bot/blob/master/CHANGELOG.md#280)

**Pull request closed without merging**
